[build]
  command = "next build"
  publish = ".next"

[build.environment]
  # Disable telemetry for cleaner build logs
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
